# Generated by Django 2.1 on 2019-04-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicial', models.FloatField(null=True)),
                ('acido_fosforico', models.FloatField(blank=True, null=True)),
                ('final_maceracion', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('lote_nro', models.PositiveIntegerField(help_text='ID lote, debe ser unico', primary_key=True, serialize=False)),
                ('observaciones', models.TextField(help_text='Comentarios,datos o informacion relevante a un lote determinado', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maceracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_nro', models.PositiveIntegerField(help_text='nro de batch correspondiente, puede ser 1 o 2')),
                ('densidad_finalizacion_maceracion', models.FloatField(blank=True, null=True)),
                ('densidad_finalizacion_lavado', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(help_text='Comentarios,datos o informacion relevante a la etapa de maceracion', max_length=200)),
                ('correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.Correccion')),
            ],
        ),
        migrations.CreateModel(
            name='OllaAguaCaliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OllaMaceracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granos', models.CharField(help_text='Tipo de grano', max_length=50)),
                ('cantidad', models.FloatField(blank=True, help_text='Cantidad expresada en kilogramos', null=True)),
                ('agua', models.CharField(help_text='Tipo de grano', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoMaceracionCoccion',
            fields=[
                ('lote_nro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cooking.Lote')),
                ('fecha_inicio', models.DateField(help_text='Fecha inicio del proceso de coccion, campo requerido')),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(help_text='Comentarios,datos o informacion relevante al proceso de coccion para un lote determinado', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='maceracion',
            name='olla_agua_caliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.OllaAguaCaliente'),
        ),
        migrations.AddField(
            model_name='maceracion',
            name='olla_maceracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.OllaMaceracion'),
        ),
        migrations.AddField(
            model_name='procesomaceracioncoccion',
            name='maceracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.Maceracion'),
        ),
    ]
