# Generated by Django 2.1 on 2019-04-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesomaceracioncoccion',
            old_name='lote_nro',
            new_name='lote',
        ),
    ]
