# Generated by Django 2.1 on 2019-04-29 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20190428_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaOllaAguaCaliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_nombre', models.CharField(choices=[('empaste', 'Empaste'), ('maceracion', 'Maceracion')], help_text='etapa nombre, solo puede ser Empaste o Maceracion', max_length=50)),
                ('etapa_hora_inicio', models.CharField(help_text='hora inicio', max_length=50)),
                ('temperatura_R', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_M', models.CharField(blank=True, max_length=50, null=True)),
                ('altura', models.CharField(blank=True, max_length=50, null=True)),
                ('agit_rec', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ollaaguacaliente',
            name='agua_dureza',
            field=models.CharField(blank=True, help_text='dureza de agua dentro de Olla caliente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ollaaguacaliente',
            name='agua_ph',
            field=models.CharField(blank=True, help_text='ph del agua dentro Olla caliente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ollaaguacaliente',
            name='filtracion_hora_inicio',
            field=models.CharField(default=django.utils.timezone.now, help_text='hora inicio de filtracion', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maceracion',
            name='batch_nro',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2)], help_text='nro de batch correspondiente, puede ser 1 o 2'),
        ),
        migrations.AlterField(
            model_name='ollamaceracion',
            name='agua',
            field=models.CharField(blank=True, help_text='Litros', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ollaaguacaliente',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.EtapaOllaAguaCaliente'),
        ),
    ]
