# Generated by Django 2.1 on 2019-04-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20190429_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo de adicion', max_length=50)),
                ('gramos', models.PositiveIntegerField(blank=True, help_text='Cantidad expresada en gramos', null=True)),
                ('hora_adicion', models.CharField(blank=True, help_text='hora de adicion', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_nro', models.PositiveIntegerField(choices=[(1, 1), (2, 2)], help_text='nro de batch correspondiente, puede ser 1 o 2')),
                ('densidad_finalizacion_hervor', models.FloatField(blank=True, null=True)),
                ('hora_fin_trasiego', models.CharField(blank=True, help_text='hora inicio', max_length=50, null=True)),
                ('observaciones', models.TextField(help_text='Comentarios,datos o informacion relevante a la etapa de coccion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaCoccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_hora_inicio', models.CharField(help_text='hora inicio', max_length=50)),
                ('etapa_nombre', models.CharField(choices=[('lavado', 'lavado'), ('aumento T', 'aumento T'), ('hervor', 'hervor'), ('reposo', 'reposo'), ('trasiego', 'trasiego')], help_text='etapa nombre, solo puede ser Lavado, Aumento T, Hervor, Reposos y Trasiego', max_length=50)),
                ('adiciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.Adicion')),
            ],
        ),
        migrations.AlterField(
            model_name='lote',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Comentarios,datos o informacion relevante a un lote determinado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maceracion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Comentarios,datos o informacion relevante a la etapa de maceracion', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='procesomaceracioncoccion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Comentarios,datos o informacion relevante al proceso de coccion para un lote determinado', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coccion',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.EtapaCoccion'),
        ),
        migrations.AddField(
            model_name='procesomaceracioncoccion',
            name='coccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking.Coccion'),
        ),
    ]
