# Generated by Django 2.2 on 2019-04-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_auto_20190429_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coccion',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='etapacoccion',
            name='adiciones',
        ),
        migrations.RemoveField(
            model_name='maceracion',
            name='correccion',
        ),
        migrations.RemoveField(
            model_name='maceracion',
            name='olla_agua_caliente',
        ),
        migrations.RemoveField(
            model_name='maceracion',
            name='olla_maceracion',
        ),
        migrations.RemoveField(
            model_name='ollaaguacaliente',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='procesomaceracioncoccion',
            name='coccion',
        ),
        migrations.RemoveField(
            model_name='procesomaceracioncoccion',
            name='maceracion',
        ),
        migrations.AddField(
            model_name='adicion',
            name='etapa_coccion',
            field=models.ForeignKey(help_text='Etapa de Coccion a la que pertenece dicha adicion', null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.EtapaCoccion'),
        ),
        migrations.AddField(
            model_name='coccion',
            name='proceso_maceracion_coccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.ProcesoMaceracionCoccion'),
        ),
        migrations.AddField(
            model_name='correccion',
            name='maceracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.Maceracion'),
        ),
        migrations.AddField(
            model_name='etapacoccion',
            name='coccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.Coccion'),
        ),
        migrations.AddField(
            model_name='etapaollaaguacaliente',
            name='olla_agua_caliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.OllaAguaCaliente'),
        ),
        migrations.AddField(
            model_name='maceracion',
            name='proceso_maceracion_coccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.ProcesoMaceracionCoccion'),
        ),
        migrations.AddField(
            model_name='ollaaguacaliente',
            name='maceracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.Maceracion'),
        ),
        migrations.AddField(
            model_name='ollamaceracion',
            name='maceracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.Maceracion'),
        ),
        migrations.AlterField(
            model_name='coccion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Comentarios,datos o informacion relevante a la etapa de coccion', max_length=200, null=True),
        ),
    ]
