# Generated by Django 2.2 on 2019-04-30 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_auto_20190429_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
